### ISSUE TITLE
[1.1.5] Segfault @ Map

### ISSUE THREAD

**Issue by vovagp** [php-ds/extension#55]
```
vovagp@debian:/tmp/ds$ php -v
PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
vovagp@debian:/tmp/ds$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```

```
vovagp@debian:/tmp/ds$ cat test.php 
<?php

function test() {
    $m = new \Ds\Map();
    for($i=0;$i<10;$i++) {
	$k = "k$i";
	$m->put($k, $i);
	$m->get($k);
	$m->remove($k);
    }
}

test();
```

```
vovagp@debian:/tmp/ds$ php -r 'echo phpversion("ds");'
1.1.5
```

```
(gdb) run /tmp/ds/test.php
Starting program: /usr/bin/php /tmp/ds/test.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
ds_htable_lookup_bucket_by_hash (table=table@entry=0x7ffff5e62840, key=key@entry=0x7ffff5e13240, hash=hash@entry=5863493)
    at /tmp/ds/1.1.5/extension-1.1.5/src/ds/ds_htable.c:349
349	        if (DS_HTABLE_BUCKET_HASH(bucket) == hash && ds_htable_bucket_key_match(bucket, key)) {
(gdb) bt
#0  ds_htable_lookup_bucket_by_hash (table=table@entry=0x7ffff5e62840, key=key@entry=0x7ffff5e13240, hash=hash@entry=5863493)
    at /tmp/ds/1.1.5/extension-1.1.5/src/ds/ds_htable.c:349
#1  0x00007fffe55b79df in ds_htable_lookup_or_next (table=0x7ffff5e62840, key=0x7ffff5e13240, bucket=bucket@entry=0x7fffffffa648)
    at /tmp/ds/1.1.5/extension-1.1.5/src/ds/ds_htable.c:660
#2  0x00007fffe55b7a92 in ds_htable_put (table=<optimized out>, key=<optimized out>, value=0x7ffff5e13250)
    at /tmp/ds/1.1.5/extension-1.1.5/src/ds/ds_htable.c:678
#3  0x00007fffe55b9a78 in ds_map_put (map=<optimized out>, key=<optimized out>, value=<optimized out>)
    at /tmp/ds/1.1.5/extension-1.1.5/src/ds/ds_map.c:53
#4  0x00007fffe55c3d92 in zim_Map_put (execute_data=0x7ffff5e131e0, return_value=<optimized out>)
    at /tmp/ds/1.1.5/extension-1.1.5/src/php/classes/php_map_ce.c:51
#5  0x00005555557a6a1a in dtrace_execute_internal ()
#6  0x000055555583b910 in ?? ()
#7  0x00005555557f6cab in execute_ex ()
#8  0x00005555557a68a8 in dtrace_execute_ex ()
#9  0x000055555583ba4d in ?? ()
#10 0x00005555557f6cab in execute_ex ()
#11 0x00005555557a68a8 in dtrace_execute_ex ()
#12 0x000055555584b597 in zend_execute ()
#13 0x00005555557b6d33 in zend_execute_scripts ()
#14 0x00005555557575d0 in php_execute_script ()
#15 0x000055555584d24a in ?? ()
#16 0x000055555563cfbd in main ()
(gdb) 
```

**Comment by rtheunissen** [comment]
This has now been fixed. See a9428f5dd9439dc9e529dec4409b9d430f4ff974

Released as 1.1.6 on PECL. ✨
